namespace FundEx.Application.Common.Mappings;
using FundEx.Application.Common.Models.Tefas;
using FundEx.Domain.Entities;
using Mapster;

public static class MappingProfile
{
    public static void RegisterMappings()
    {
        TypeAdapterConfig<DagilimResult, FundDailyData>.NewConfig()
            .Map(dest => dest.Stock, src => src.Hs)
            .Map(dest => dest.GovernmentBond, src => src.Dt)
            .Map(dest => dest.FxDenominatedGovernmentDebt, src => src.D)
            .Map(dest => dest.TreasuryBill, src => src.Hb)
            .Map(dest => dest.CommercialPaper, src => src.Fb)
            .Map(dest => dest.CorporateBond, src => src.Ost)
            .Map(dest => dest.AssetBackedSecurities, src => src.Vdm)
            .Map(dest => dest.GovernmentExternalDebt, src => src.Db)
            .Map(dest => dest.CorporateExternalDebt, src => src.Osdb)
            .Map(dest => dest.GovernmentLeaseCertificates, src => src.Kks)
            .Map(dest => dest.GovernmentLeaseCertificatesTl, src => src.Kkstl)
            .Map(dest => dest.GovernmentLeaseCertificatesFx, src => src.Kksd)
            .Map(dest => dest.LeaseCertificatesNonInvestment, src => src.Kksyd)
            .Map(dest => dest.CorporateLeaseCertificates, src => src.Osks)
            .Map(dest => dest.ReverseRepo, src => src.Tr)
            .Map(dest => dest.Repo, src => src.R)
            .Map(dest => dest.BistCommittedTradingSale, src => src.Btas)
            .Map(dest => dest.BistCommittedTradingPurchase, src => src.Btaa)
            .Map(dest => dest.TakasbankMoneyMarket, src => src.Tpp)
            .Map(dest => dest.BorsaIstanbulMoneyMarket, src => src.Bpp)
            .Map(dest => dest.DepositFx, src => src.Vmd)
            .Map(dest => dest.DepositTl, src => src.Vmtl)
            .Map(dest => dest.Deposit, src => src.Vm)
            .Map(dest => dest.DepositGold, src => src.Vmau)
            .Map(dest => dest.ParticipationAccountFx, src => src.Khd)
            .Map(dest => dest.ParticipationAccountTl, src => src.Khtl)
            .Map(dest => dest.ParticipationAccount, src => src.Kh)
            .Map(dest => dest.ParticipationAccountGold, src => src.Khau)
            .Map(dest => dest.PreciousMetals, src => src.Km)
            .Map(dest => dest.PreciousMetalsEtf, src => src.Kmbyf)
            .Map(dest => dest.PreciousMetalsGovernmentDebt, src => src.Kmkba)
            .Map(dest => dest.PreciousMetalsLeaseCertificates, src => src.Kmkks)
            .Map(dest => dest.ForeignEtf, src => src.Ybyf)
            .Map(dest => dest.ForeignStock, src => src.Yhs)
            .Map(dest => dest.EtfParticipationShares, src => src.Ybkb)
            .Map(dest => dest.ForeignPartnershipDebt, src => src.Ybosb)
            .Map(dest => dest.ForeignDebtInstruments, src => src.Yba)
            .Map(dest => dest.ForeignSecurities, src => src.Ymk)
            .Map(dest => dest.InvestmentFundShares, src => src.Yyf)
            .Map(dest => dest.FuturesCashCollateral, src => src.Vint)
            .Map(dest => dest.Other, src => src.Bb)
            .Map(dest => dest.ExchangeTradedFund, src => src.Byf)
            .Map(dest => dest.OtherPartnership, src => src.Dot)
            .Map(dest => dest.Eurobond, src => src.Eut)
            .Map(dest => dest.FundGovernmentDebt, src => src.Fkb)
            .Map(dest => dest.RealEstateTrading, src => src.Gas)
            .Map(dest => dest.VentureCapitalInstitutionDebt, src => src.Gsykb)
            .Map(dest => dest.VentureCapitalInvestment, src => src.Gsyy)
            .Map(dest => dest.RealEstateInstitutionDebt, src => src.Gykb)
            .Map(dest => dest.RealEstateInvestment, src => src.Gyy)
            .Map(dest => dest.GovernmentDebtInstruments, src => src.Kba)
            .Map(dest => dest.LeasingTransactionDebt, src => src.Kibd)
            .Map(dest => dest.PrivateSectorNonInvestment, src => src.Oksyd)
            .Map(dest => dest.Bond, src => src.T)
            .Ignore(dest => dest.Id)
            .Ignore(dest => dest.FundId)
            .Ignore(dest => dest.Fund)
            .Ignore(dest => dest.Date)
            .Ignore(dest => dest.Price)
            .Ignore(dest => dest.ShareCount)
            .Ignore(dest => dest.InvestorCount)
            .Ignore(dest => dest.PortfolioSize)
            .Ignore(dest => dest.ExchangeBulletinPrice)
            .Ignore(dest => dest.CreatedDate)
            .Ignore(dest => dest.UpdatedDate);
    }
}
